### ISSUE TITLE
Mutator method generation for reference types

### ISSUE THREAD

**Issue by silver-snoopy** [tornaia/matcher-generator-for-java#16]
If an object has a custom reference type like ExampleChildObject, then the matchergenerator should generate the mutator method in the following way:

public ExampleParentObjectMatcher exampleChildObject(Matcher<ExampleChildObject> childObjectMatcher) {
...content
}

In this way i can use the generated matcher of the ExampleChildObject :)

Regards,
Dani

**Comment by tornaia** [comment]
Fixed but

> public ExampleParentObjectMatcher exampleChildObject(Matcher childObjectMatcher) {
> ...content
> }

will be

public ExampleParentObjectMatcher exampleChildObject(Matcher<ChildObject> childObject) {
...content
}

Maybe you also wrote that but github does not handle these special characters (<> very well). You have to escape it ;)

Please confirm if the bug is fixed or will close the ticket soon.

**Comment by silver-snoopy** [comment]
Thank you for the quick fix it was exactly what i wanted :+1:
